### ISSUE TITLE
100% open source?

### ISSUE THREAD

**Issue by mamama1** [monotech/NuXT#2]
Hi,

awesome work! Is this 100% open source so I could in theory get all the parts and firmware by myself or would there be missing any parts?
Not that it would be very feasable... :-)

Thanks!

**Comment by RigoLigoRLC** [comment]
I think it is possible. Now I'm looking for all the parts and finding a way to do it, including the VBIOS that wasn't provided with the project and the PIC MCU firmware which is also open-source. The hardware part isn't very hard though.

**Comment by mamama1** [comment]
The VBIOS is probably under copyright and may be extracted from a working Trident or could probably be available somewhere on the interwebs...
Totally missed the PIC MCU, that one is for the AT/XT Keyboard interface, right?

Would be really nice if everything would be made available to make this board on your own. I highly doubt that this would lower the profit on selling the boards and kits in a significant degree cause I don't think that there are many people out there who'd go into the hassle to acquire the parts and build this totally from scratch by themselves.

For me it isn't to save money but because it is fun for me to acquire everything by myself instead of buying a kit or let alone a finished product. I'd like to still support the creator of this project somehow.

**Comment by RigoLigoRLC** [comment]
Now I found the VBIOS, just through searching online. That one was easy. AT2XT is also a open sourced GitHub repo which you can just download and compile, so that's not really a problem.

I'm also trying to make it on my own, but this time it's really for saving costs. I live in China where most of the components were just available online for a resonable price and shipping fee :p but also for fun. I'm preparing these stuff so maybe sometime I can add some tips in README or somewhere else by a pull-request for others to make the kit on their own.

**Comment by monotech** [comment]
> The VBIOS is probably under copyright and may be extracted from a working Trident or could probably be available somewhere on the interwebs...
> Totally missed the PIC MCU, that one is for the AT/XT Keyboard interface, right?
> 
> Would be really nice if everything would be made available to make this board on your own. I highly doubt that this would lower the profit on selling the boards and kits in a significant degree cause I don't think that there are many people out there who'd go into the hassle to acquire the parts and build this totally from scratch by themselves.
> 
> For me it isn't to save money but because it is fun for me to acquire everything by myself instead of buying a kit or let alone a finished product. I'd like to still support the creator of this project somehow.

Hello
I do sell kits and assembled boards. The main rare chip is the TVGA9000i, and stock depends on how many of those I have.
https://monotech.fwscart.com/NuXT_-_MicroATX_Turbo_XT_-_955MHz,_832K_RAM,_XT-CF,_SVGA,_Floppy,_Serial/p6083514_19777986.aspx
