### ISSUE TITLE
CGA 40x25 mode

### ISSUE THREAD

**Issue by eltair** [monotech/NuXT#3]
I have an official IBM CGA card and would like the system to boot in 40 column mode, but the switch for that doesn't seem to work. The machine always boots in 80 column mode. I can switch to 40 columns successfully from dos using the mode 40 command. Any ideas? Thank you.

**Comment by eltair** [comment]
FYI, I'm no longer using the CGA card with this board, although I'm still curious what the switches for video card type actually do. They don't seem to have any effect on my system.

**Comment by skiselev** [comment]
It's a bug.... The BIOS was initially written for Xi 8088, which has only one switch (monochrome/color). And so it ignores the 40x25 mode.
I've created an issue for the BIOS: https://github.com/skiselev/8088_bios/issues/3

**Comment by skiselev** [comment]
I've committed the fix for this issue to the BIOS repository. It will be available in the next BIOS release:
https://github.com/skiselev/8088_bios/commit/d95b9110b5713eecce2dcd4c15e561234f214daa

**Comment by skiselev** [comment]
The fix is released in v0.9.7 https://github.com/skiselev/8088_bios/commit/08c673eb063bd22bcfc3bcb5bacfad20ed8876e8

**Comment by eltair** [comment]
@skiselev Thanks for fixing this! I tested it and it works, although I have another issue with CGA booting that I will submit separately.
