### ISSUE TITLE
System ROM build instructions

### ISSUE THREAD

**Issue by eltair** [monotech/NuXT#6]
I noticed that the NuXT system ROM is built a bit differently than the upstream releases from https://github.com/skiselev/8088_bios. For example, the BIOS is located at C000 instead of A000. Also the xt-ide version is different. It would be nice to have docs/scripts for how to build the ROM as described in the NuXT manual. Thank you.

**Comment by skiselev** [comment]
The BIOS start address and size had changed in the recent (v0.9.7) update since I needed more space to accommodate RTC support. I can't comment on the XT-IDE version.

**Comment by eltair** [comment]
Ahh, okay thanks.
